// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auction.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Auction struct {
	ID                   string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	OrganizerID          int64                  `protobuf:"varint,4,opt,name=OrganizerID,proto3" json:"OrganizerID,omitempty"`
	MaxParticipants      int32                  `protobuf:"varint,5,opt,name=MaxParticipants,proto3" json:"MaxParticipants,omitempty"`
	ParticipantsNumber   int32                  `protobuf:"varint,6,opt,name=ParticipantsNumber,proto3" json:"ParticipantsNumber,omitempty"`
	StartsAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=StartsAt,proto3" json:"StartsAt,omitempty"`
	EndsAt               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=EndsAt,proto3" json:"EndsAt,omitempty"`
	Status               string                 `protobuf:"bytes,9,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Auction) Reset()         { *m = Auction{} }
func (m *Auction) String() string { return proto.CompactTextString(m) }
func (*Auction) ProtoMessage()    {}
func (*Auction) Descriptor() ([]byte, []int) {
	return fileDescriptor_622f477c3a3f2896, []int{0}
}

func (m *Auction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auction.Unmarshal(m, b)
}
func (m *Auction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auction.Marshal(b, m, deterministic)
}
func (m *Auction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auction.Merge(m, src)
}
func (m *Auction) XXX_Size() int {
	return xxx_messageInfo_Auction.Size(m)
}
func (m *Auction) XXX_DiscardUnknown() {
	xxx_messageInfo_Auction.DiscardUnknown(m)
}

var xxx_messageInfo_Auction proto.InternalMessageInfo

func (m *Auction) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Auction) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Auction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Auction) GetOrganizerID() int64 {
	if m != nil {
		return m.OrganizerID
	}
	return 0
}

func (m *Auction) GetMaxParticipants() int32 {
	if m != nil {
		return m.MaxParticipants
	}
	return 0
}

func (m *Auction) GetParticipantsNumber() int32 {
	if m != nil {
		return m.ParticipantsNumber
	}
	return 0
}

func (m *Auction) GetStartsAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartsAt
	}
	return nil
}

func (m *Auction) GetEndsAt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndsAt
	}
	return nil
}

func (m *Auction) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Auction)(nil), "protobuf.Auction")
}

func init() {
	proto.RegisterFile("auction.proto", fileDescriptor_622f477c3a3f2896)
}

var fileDescriptor_622f477c3a3f2896 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x6b, 0x83, 0x40,
	0x10, 0xc5, 0x51, 0xab, 0x31, 0x13, 0xda, 0xc2, 0x50, 0xca, 0x92, 0x4b, 0xa5, 0x27, 0x4f, 0x0a,
	0x29, 0xf4, 0x9e, 0x62, 0x0f, 0x1e, 0xfa, 0x07, 0x93, 0x53, 0x6f, 0xab, 0xdd, 0xca, 0x42, 0xd4,
	0x65, 0x77, 0x84, 0xd2, 0x6f, 0xd9, 0x6f, 0x54, 0x5c, 0x63, 0x91, 0x52, 0xc8, 0x69, 0x78, 0x6f,
	0x7e, 0xbf, 0xcb, 0x83, 0x73, 0xde, 0x57, 0x24, 0xbb, 0x36, 0x51, 0xba, 0xa3, 0x0e, 0x43, 0x7b,
	0xca, 0xfe, 0x63, 0x7d, 0x53, 0x77, 0x5d, 0x7d, 0x10, 0xe9, 0x54, 0xa4, 0x24, 0x1b, 0x61, 0x88,
	0x37, 0x6a, 0x44, 0x6f, 0xbf, 0x5d, 0x58, 0x6c, 0x47, 0x19, 0x2f, 0xc0, 0xcd, 0x33, 0xe6, 0x44,
	0x4e, 0xbc, 0x2c, 0xdc, 0x3c, 0xc3, 0x2b, 0xf0, 0xf7, 0x92, 0x0e, 0x82, 0xb9, 0xb6, 0x1a, 0x03,
	0x46, 0xb0, 0xca, 0x84, 0xa9, 0xb4, 0x54, 0x83, 0xc4, 0x3c, 0xfb, 0x9b, 0x57, 0x03, 0xf1, 0xa2,
	0x6b, 0xde, 0xca, 0x2f, 0xa1, 0xf3, 0x8c, 0x9d, 0x45, 0x4e, 0xec, 0x15, 0xf3, 0x0a, 0x63, 0xb8,
	0x7c, 0xe2, 0x9f, 0xaf, 0x5c, 0x93, 0xac, 0xa4, 0xe2, 0x2d, 0x19, 0xe6, 0x47, 0x4e, 0xec, 0x17,
	0x7f, 0x6b, 0x4c, 0x00, 0xe7, 0xf9, 0xb9, 0x6f, 0x4a, 0xa1, 0x59, 0x60, 0xe1, 0x7f, 0x3e, 0x78,
	0x0f, 0xe1, 0x8e, 0xb8, 0x26, 0xb3, 0x25, 0xb6, 0x88, 0x9c, 0x78, 0xb5, 0x59, 0x27, 0xe3, 0x06,
	0xc9, 0xb4, 0x41, 0xb2, 0x9f, 0x36, 0x28, 0x7e, 0x59, 0xdc, 0x40, 0xf0, 0xd8, 0xbe, 0x0f, 0x56,
	0x78, 0xd2, 0x3a, 0x92, 0x78, 0x0d, 0xc1, 0x8e, 0x38, 0xf5, 0x86, 0x2d, 0xed, 0x08, 0xc7, 0xf4,
	0xe0, 0xbf, 0x79, 0xa9, 0x2a, 0xcb, 0xc0, 0xaa, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x9a, 0x6b, 0xe3, 0x9d, 0x01, 0x00, 0x00,
}
