// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAuctionInfoRequest struct {
	AuctionId            string   `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuctionInfoRequest) Reset()         { *m = GetAuctionInfoRequest{} }
func (m *GetAuctionInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuctionInfoRequest) ProtoMessage()    {}
func (*GetAuctionInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{0}
}

func (m *GetAuctionInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuctionInfoRequest.Unmarshal(m, b)
}
func (m *GetAuctionInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuctionInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetAuctionInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuctionInfoRequest.Merge(m, src)
}
func (m *GetAuctionInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuctionInfoRequest.Size(m)
}
func (m *GetAuctionInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuctionInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuctionInfoRequest proto.InternalMessageInfo

func (m *GetAuctionInfoRequest) GetAuctionId() string {
	if m != nil {
		return m.AuctionId
	}
	return ""
}

type GetAuctionInfoResponse struct {
	Auction              []byte   `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuctionInfoResponse) Reset()         { *m = GetAuctionInfoResponse{} }
func (m *GetAuctionInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuctionInfoResponse) ProtoMessage()    {}
func (*GetAuctionInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{1}
}

func (m *GetAuctionInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuctionInfoResponse.Unmarshal(m, b)
}
func (m *GetAuctionInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuctionInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetAuctionInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuctionInfoResponse.Merge(m, src)
}
func (m *GetAuctionInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuctionInfoResponse.Size(m)
}
func (m *GetAuctionInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuctionInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuctionInfoResponse proto.InternalMessageInfo

func (m *GetAuctionInfoResponse) GetAuction() []byte {
	if m != nil {
		return m.Auction
	}
	return nil
}

func (m *GetAuctionInfoResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AuctionsFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuctionsFilter) Reset()         { *m = AuctionsFilter{} }
func (m *AuctionsFilter) String() string { return proto.CompactTextString(m) }
func (*AuctionsFilter) ProtoMessage()    {}
func (*AuctionsFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{2}
}

func (m *AuctionsFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuctionsFilter.Unmarshal(m, b)
}
func (m *AuctionsFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuctionsFilter.Marshal(b, m, deterministic)
}
func (m *AuctionsFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionsFilter.Merge(m, src)
}
func (m *AuctionsFilter) XXX_Size() int {
	return xxx_messageInfo_AuctionsFilter.Size(m)
}
func (m *AuctionsFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionsFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionsFilter proto.InternalMessageInfo

type SearchAuctionsRequest struct {
	SearchRequest        string          `protobuf:"bytes,1,opt,name=search_request,json=searchRequest,proto3" json:"search_request,omitempty"`
	Filter               *AuctionsFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Page                 int32           `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchAuctionsRequest) Reset()         { *m = SearchAuctionsRequest{} }
func (m *SearchAuctionsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAuctionsRequest) ProtoMessage()    {}
func (*SearchAuctionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{3}
}

func (m *SearchAuctionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAuctionsRequest.Unmarshal(m, b)
}
func (m *SearchAuctionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAuctionsRequest.Marshal(b, m, deterministic)
}
func (m *SearchAuctionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAuctionsRequest.Merge(m, src)
}
func (m *SearchAuctionsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAuctionsRequest.Size(m)
}
func (m *SearchAuctionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAuctionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAuctionsRequest proto.InternalMessageInfo

func (m *SearchAuctionsRequest) GetSearchRequest() string {
	if m != nil {
		return m.SearchRequest
	}
	return ""
}

func (m *SearchAuctionsRequest) GetFilter() *AuctionsFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *SearchAuctionsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type SearchAuctionsResponse struct {
	Match                int64    `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Auctions             []byte   `protobuf:"bytes,4,opt,name=auctions,proto3" json:"auctions,omitempty"`
	PageNum              int32    `protobuf:"varint,5,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAuctionsResponse) Reset()         { *m = SearchAuctionsResponse{} }
func (m *SearchAuctionsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchAuctionsResponse) ProtoMessage()    {}
func (*SearchAuctionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{4}
}

func (m *SearchAuctionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAuctionsResponse.Unmarshal(m, b)
}
func (m *SearchAuctionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAuctionsResponse.Marshal(b, m, deterministic)
}
func (m *SearchAuctionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAuctionsResponse.Merge(m, src)
}
func (m *SearchAuctionsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchAuctionsResponse.Size(m)
}
func (m *SearchAuctionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAuctionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAuctionsResponse proto.InternalMessageInfo

func (m *SearchAuctionsResponse) GetMatch() int64 {
	if m != nil {
		return m.Match
	}
	return 0
}

func (m *SearchAuctionsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SearchAuctionsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SearchAuctionsResponse) GetAuctions() []byte {
	if m != nil {
		return m.Auctions
	}
	return nil
}

func (m *SearchAuctionsResponse) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type GetProductInfoRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductInfoRequest) Reset()         { *m = GetProductInfoRequest{} }
func (m *GetProductInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductInfoRequest) ProtoMessage()    {}
func (*GetProductInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{5}
}

func (m *GetProductInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductInfoRequest.Unmarshal(m, b)
}
func (m *GetProductInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetProductInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductInfoRequest.Merge(m, src)
}
func (m *GetProductInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductInfoRequest.Size(m)
}
func (m *GetProductInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductInfoRequest proto.InternalMessageInfo

func (m *GetProductInfoRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type GetProductInfoResponse struct {
	Product              []byte   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductInfoResponse) Reset()         { *m = GetProductInfoResponse{} }
func (m *GetProductInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductInfoResponse) ProtoMessage()    {}
func (*GetProductInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{6}
}

func (m *GetProductInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductInfoResponse.Unmarshal(m, b)
}
func (m *GetProductInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetProductInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductInfoResponse.Merge(m, src)
}
func (m *GetProductInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductInfoResponse.Size(m)
}
func (m *GetProductInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductInfoResponse proto.InternalMessageInfo

func (m *GetProductInfoResponse) GetProduct() []byte {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetProductInfoResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ProductsFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductsFilter) Reset()         { *m = ProductsFilter{} }
func (m *ProductsFilter) String() string { return proto.CompactTextString(m) }
func (*ProductsFilter) ProtoMessage()    {}
func (*ProductsFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{7}
}

func (m *ProductsFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductsFilter.Unmarshal(m, b)
}
func (m *ProductsFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductsFilter.Marshal(b, m, deterministic)
}
func (m *ProductsFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductsFilter.Merge(m, src)
}
func (m *ProductsFilter) XXX_Size() int {
	return xxx_messageInfo_ProductsFilter.Size(m)
}
func (m *ProductsFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductsFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ProductsFilter proto.InternalMessageInfo

type SearchProductsRequest struct {
	SearchRequest        string          `protobuf:"bytes,1,opt,name=search_request,json=searchRequest,proto3" json:"search_request,omitempty"`
	Filter               *ProductsFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Page                 int32           `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchProductsRequest) Reset()         { *m = SearchProductsRequest{} }
func (m *SearchProductsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchProductsRequest) ProtoMessage()    {}
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{8}
}

func (m *SearchProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsRequest.Unmarshal(m, b)
}
func (m *SearchProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsRequest.Marshal(b, m, deterministic)
}
func (m *SearchProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsRequest.Merge(m, src)
}
func (m *SearchProductsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchProductsRequest.Size(m)
}
func (m *SearchProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsRequest proto.InternalMessageInfo

func (m *SearchProductsRequest) GetSearchRequest() string {
	if m != nil {
		return m.SearchRequest
	}
	return ""
}

func (m *SearchProductsRequest) GetFilter() *ProductsFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *SearchProductsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type SearchProductsResponse struct {
	Match                int64    `protobuf:"varint,1,opt,name=match,proto3" json:"match,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Products             []byte   `protobuf:"bytes,4,opt,name=products,proto3" json:"products,omitempty"`
	PageNum              int32    `protobuf:"varint,5,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchProductsResponse) Reset()         { *m = SearchProductsResponse{} }
func (m *SearchProductsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchProductsResponse) ProtoMessage()    {}
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d511c217b3936007, []int{9}
}

func (m *SearchProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchProductsResponse.Unmarshal(m, b)
}
func (m *SearchProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchProductsResponse.Marshal(b, m, deterministic)
}
func (m *SearchProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchProductsResponse.Merge(m, src)
}
func (m *SearchProductsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchProductsResponse.Size(m)
}
func (m *SearchProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchProductsResponse proto.InternalMessageInfo

func (m *SearchProductsResponse) GetMatch() int64 {
	if m != nil {
		return m.Match
	}
	return 0
}

func (m *SearchProductsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SearchProductsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SearchProductsResponse) GetProducts() []byte {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *SearchProductsResponse) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAuctionInfoRequest)(nil), "protobuf.GetAuctionInfoRequest")
	proto.RegisterType((*GetAuctionInfoResponse)(nil), "protobuf.GetAuctionInfoResponse")
	proto.RegisterType((*AuctionsFilter)(nil), "protobuf.AuctionsFilter")
	proto.RegisterType((*SearchAuctionsRequest)(nil), "protobuf.SearchAuctionsRequest")
	proto.RegisterType((*SearchAuctionsResponse)(nil), "protobuf.SearchAuctionsResponse")
	proto.RegisterType((*GetProductInfoRequest)(nil), "protobuf.GetProductInfoRequest")
	proto.RegisterType((*GetProductInfoResponse)(nil), "protobuf.GetProductInfoResponse")
	proto.RegisterType((*ProductsFilter)(nil), "protobuf.ProductsFilter")
	proto.RegisterType((*SearchProductsRequest)(nil), "protobuf.SearchProductsRequest")
	proto.RegisterType((*SearchProductsResponse)(nil), "protobuf.SearchProductsResponse")
}

func init() {
	proto.RegisterFile("search_service.proto", fileDescriptor_d511c217b3936007)
}

var fileDescriptor_d511c217b3936007 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xc7, 0x31, 0x60, 0x3e, 0xa6, 0x05, 0x55, 0x2b, 0x40, 0x2e, 0x52, 0x55, 0xb4, 0x52, 0x25,
	0x4e, 0xb4, 0xa2, 0x52, 0xef, 0xed, 0xa1, 0x15, 0x3d, 0x44, 0x89, 0x51, 0x2e, 0xb9, 0x20, 0x63,
	0x96, 0x60, 0x29, 0xd8, 0xce, 0xee, 0x3a, 0x4f, 0x90, 0x37, 0xc8, 0x23, 0xe6, 0x45, 0x22, 0x76,
	0x67, 0xf1, 0x27, 0x28, 0x07, 0x4e, 0xf0, 0x1f, 0xcf, 0xce, 0xfe, 0x67, 0x7f, 0x33, 0x30, 0x10,
	0xcc, 0xe3, 0xfe, 0x6e, 0x25, 0x18, 0x7f, 0x0a, 0x7c, 0x36, 0x8b, 0x79, 0x24, 0x23, 0xd2, 0x51,
	0x3f, 0xeb, 0x64, 0x4b, 0x7f, 0xc1, 0xf0, 0x1f, 0x93, 0xbf, 0x13, 0x5f, 0x06, 0x51, 0xb8, 0x08,
	0xb7, 0x91, 0xcb, 0x1e, 0x13, 0x26, 0x24, 0xf9, 0x02, 0xe0, 0xe9, 0xe8, 0x2a, 0xd8, 0x38, 0xd6,
	0xc4, 0x9a, 0x76, 0xdd, 0x2e, 0x46, 0x16, 0x1b, 0xfa, 0x1f, 0x46, 0xc5, 0x73, 0x22, 0x8e, 0x42,
	0xc1, 0x88, 0x03, 0x6d, 0x4c, 0x53, 0xa7, 0x3e, 0xba, 0x46, 0x92, 0x11, 0xb4, 0x84, 0xf4, 0x64,
	0x22, 0x9c, 0xfa, 0xc4, 0x9a, 0xda, 0x2e, 0x2a, 0xfa, 0x09, 0xfa, 0x58, 0x48, 0xfc, 0x0d, 0x1e,
	0x24, 0xe3, 0xf4, 0xd9, 0x82, 0xe1, 0x52, 0x19, 0x37, 0x1f, 0x8c, 0xad, 0x6f, 0xd0, 0xc7, 0x8e,
	0xb8, 0x8e, 0xa0, 0xb5, 0x9e, 0x8e, 0x9a, 0xb4, 0x1f, 0xd0, 0xda, 0xaa, 0x52, 0xea, 0xaa, 0x0f,
	0x73, 0x67, 0x66, 0x3a, 0x9e, 0xe5, 0xaf, 0x72, 0x31, 0x8f, 0x10, 0x68, 0xc6, 0xde, 0x3d, 0x73,
	0x1a, 0xca, 0x9a, 0xfa, 0x4f, 0x5f, 0x2c, 0x18, 0x15, 0x6d, 0x60, 0x97, 0x03, 0xb0, 0xf7, 0x9e,
	0xf4, 0x77, 0xea, 0xfa, 0x86, 0xab, 0xc5, 0xa9, 0x0e, 0x0f, 0xd9, 0x8c, 0xf3, 0x88, 0xab, 0xea,
	0x5d, 0x57, 0x0b, 0x32, 0x86, 0x0e, 0x3e, 0x8d, 0x70, 0x9a, 0xea, 0xa9, 0x8e, 0x9a, 0x7c, 0x86,
	0xce, 0xc1, 0xc2, 0x2a, 0x4c, 0xf6, 0x8e, 0xad, 0x6a, 0xb5, 0x0f, 0xfa, 0x2a, 0xd9, 0x23, 0xb2,
	0x6b, 0x1e, 0x6d, 0x12, 0x5f, 0x16, 0x90, 0xc5, 0x3a, 0x9a, 0x41, 0x86, 0x91, 0x23, 0xb2, 0xdc,
	0xb9, 0x14, 0x19, 0xa6, 0x19, 0x64, 0x28, 0xcf, 0x21, 0xc3, 0x42, 0x65, 0x64, 0xe6, 0xc3, 0xe5,
	0x90, 0xe5, 0xaf, 0x7a, 0x27, 0xb2, 0xd4, 0xc6, 0x65, 0x91, 0xe1, 0xd3, 0x1c, 0x91, 0x19, 0x7d,
	0x06, 0xd9, 0xfc, 0xb5, 0x0e, 0x3d, 0xed, 0x6a, 0xa9, 0xf7, 0x90, 0xdc, 0x00, 0xa4, 0xfb, 0x43,
	0xbe, 0xa6, 0xbd, 0x56, 0x6e, 0xe3, 0x78, 0x72, 0x3a, 0x41, 0x77, 0x47, 0x6b, 0xe4, 0x16, 0xfa,
	0xf9, 0x61, 0xcd, 0x96, 0xad, 0xdc, 0xa6, 0x6c, 0xd9, 0xea, 0x39, 0xa7, 0x35, 0x74, 0x8a, 0xaf,
	0x59, 0x70, 0x5a, 0x1e, 0xc2, 0x82, 0xd3, 0x8a, 0x69, 0xcb, 0x3a, 0x35, 0x8c, 0xca, 0x4e, 0x0b,
	0x43, 0x54, 0x76, 0x5a, 0xc4, 0x4b, 0x6b, 0x7f, 0xec, 0xbb, 0xc6, 0xf7, 0x78, 0xbd, 0x6e, 0xa9,
	0xcc, 0x9f, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0xe0, 0x13, 0xcc, 0xfb, 0x04, 0x00, 0x00,
}
